### ISSUE TITLE
Not working after latest discord update

### ISSUE THREAD

**Issue by pizzadriver** [rauenzi/BetterDiscordApp#130] opened 2019-01-15 18:30 UTC
It just doesn't show any affect anymore, just the default discord. Nothing in the settings of better-discord.

**Comment by rauenzi** [comment] 2019-01-15 18:32
Try the repair option in the installer and/or reinstalling before opening an issue. Also a duplicate of #129

**Closed by rauenzi** 2019-01-15 18:32 UTC
