### ISSUE TITLE
[Bug] Program Crash

### ISSUE THREAD

**Issue by sinnx3** [rauenzi/BetterDiscordApp#568] opened 2021-03-04 19:29 UTC
**Describe the Bug**
Program crashes after certain combined keystrokes

**To Reproduce**
Shift + Enter in message box on latest windows stable release

**Expected Behavior**
Add a new line to the text box

**Screenshots**

N/A

**Discord Version**
Stable 78454 (77fa498)

**Additional Context**

**Comment by Tropix126** [comment] 2021-03-04 19:31
Known issue and duplicate. Has already been fixed in the latest injector and can be fixed by reinstalling.

**Comment by rauenzi** [comment] 2021-03-04 19:31
Please try reinstalling BD, it is likely a duplicate of #540

**Comment by Reqon** [comment] 2021-03-04 20:21
download installer > repair select every issue below > it will reinstall bd and disable some plugins activate them again // works for me

**Comment by poyqu** [comment] 2021-03-04 21:17
The "fix" worked for me, but when I re-enabled my plugins it crashed.

**Comment by rauenzi** [comment] 2021-03-04 23:11
It sounds like a specific plugin is having an issue then, once you figure out which one causes it you can file an issue with that developer.

**Comment by TheReaperr** [comment] 2021-03-05 08:57
Mine crashes when I press the 'custom css' tab. No plugins / themes / whatever loaded.

**Comment by jM1pOpJhre-mJaMOFOMt** [comment] 2021-03-05 17:26
> It sounds like a specific plugin is having an issue then, once you figure out which one causes it you can file an issue with that developer.

![download (1)](https://user-images.githubusercontent.com/53131588/110150978-be85be80-7d94-11eb-8a41-70e96a8281be.png)

Having this option enabled seems to cause the crash. (This option is under Text & Images)

**Comment by JohnDo192** [comment] 2021-03-05 20:02
Managed to fix it by going to Settings, Text and Images and **disabling this**
![image](https://user-images.githubusercontent.com/80127487/110167449-aa21e000-7ded-11eb-8d0c-a2f9a7ce7934.png)

**Comment by Tropix126** [comment] 2021-03-05 20:06
> Managed to fix it by going to Settings, Text and Images and **disabling this**
> ![image](https://user-images.githubusercontent.com/80127487/110167449-aa21e000-7ded-11eb-8d0c-a2f9a7ce7934.png)

just reinstall BBD.

**Closed** 2021-03-24 21:16 UTC
Labels: bug
