### ISSUE TITLE
Doesnt work at all on stable16

### ISSUE THREAD

**Issue by shiewa** [rauenzi/BetterDiscordApp#156] opened 2019-04-06 17:35 UTC
Betterdiscord is getting injected with betterdiscordctl, but if i start Discord there are no themes, plugins or other BetterDiscord buttons in the settings.
OS: Arch Linux with latest updates
Discord Version: DiscordCanary 0.0.74

**Comment by rauenzi** [comment] 2019-04-06 19:21
Duplicate of your other issue #155

**Comment by shiewa** [comment] 2019-04-07 07:03
No, its no duplicate. This issue is on stable16 and this occured just since 0.0.74 and the other issue exists much longer. Furthermore is here BetterDiscord not loaded, but Discord starts, on the other issue it crashes with an error.

**Comment by rauenzi** [comment] 2019-04-07 10:54
Sorry I misread the other one let me swap them around.

**Comment by rauenzi** [comment] 2019-04-07 10:56
This latest version of canary uses a beta version of electron that BBD does not support at the moment.

**Comment by rauenzi** [comment] 2019-04-10 17:24
Also as a note: The Linux installer for BBD is not managed by me and is using the old injection method that was deprecated last year. I think this is of importance because my Windows installation worked fine with Canary so it is possible the outdated injection method is broken with this version of Canary. I have already informed the person (last year) that runs the Linux installer exactly what needs to change but it hasn't been updated yet.

**Comment by rauenzi** [comment] 2019-04-21 14:37
BBD works for Canary again, including the injection.

**Closed by rauenzi** 2019-04-21 14:37 UTC
