### ISSUE TITLE
ReferenceError: Cannot access 'fs' before initialization

### ISSUE THREAD

**Issue by testheyheyhey** [rauenzi/BetterDiscordApp#601] opened 2021-03-24 20:47 UTC
I had it on my imac and today it removed so i was gonna get it back and when i tried to install it this showed "ReferenceError: Cannot access 'fs' before initialization" how can I fix cus I want it for discord & when I remove it to download it back the same thing pops up
<img width="728" alt="Screen Shot 2021-03-24 at 4 47 07 PM" src="https://user-images.githubusercontent.com/78468878/112381117-9668eb80-8cc0-11eb-8f3a-8f7dbc7266ca.png">
<img width="753" alt="Screen Shot 2021-03-24 at 4 47 11 PM" src="https://user-images.githubusercontent.com/78468878/112381132-99fc7280-8cc0-11eb-80a2-9bceb3d45733.png">

**Comment by AmanA007** [comment] 2021-03-24 21:01
I am having the same issue.

**Comment by AvaQueen-Official** [comment] 2021-03-24 21:08
Same issue

**Comment by Curtis-D** [comment] 2021-03-24 21:09
I know you're not doing it on purpose but there's lots of duplicate issues here and no need to reply with "same issue" on each separate issue.

**Comment by rauenzi** [comment] 2021-03-24 21:10
Duplicate of #600

**Closed by rauenzi** 2021-03-24 21:10 UTC
Labels: bug
