### ISSUE TITLE
[Bug] Will not start on PTB and Canary

### ISSUE THREAD

**Issue by master3395** [rauenzi/BetterDiscordApp#577] opened 2021-03-08 22:43 UTC
Works fine on stable:
Stable 78727 (b2380a5)
BBD 0.3.5
Host 0.0.309
Injector 0.6.2
Windows 10 64-Bit (10.0.19042)

Not working:
Ptb 78803 (7567bOe)

Canary 78827 (8f93920)
Host 1.0.25

**Comment by rauenzi** [comment] 2021-03-08 22:49
This is known and duplicate of #548

**Closed by rauenzi** 2021-03-08 22:49 UTC
Labels: bug
