### ISSUE TITLE
[Bug] BetterDiscord with Discord Stable/PTB not working with macOS Big Sur

### ISSUE THREAD

**Issue by EmreTech** [rauenzi/BetterDiscordApp#594] opened 2021-03-20 01:11 UTC
**Describe the Bug**
So I have macOS Big Sur 11.0.1, and Discord PTB installed. When I used the file from the latest pre-release, the app opens, but no window opens. I then tried Discord Stable and macOS prompted me to delete the app because it's not working properly.

**To Reproduce**
Attempt to install the pre-release on macOS Big Sur.

**Expected Behavior**
I expected the window to open and Discord would launch.

**Discord Version**
Tried both Discord Stable and PTB.

**Comment by EmreTech** [comment] 2021-03-20 03:19
Update: After using the BBD installer on stable, it's working now. Still not working on PTB though.

**Comment by rauenzi** [comment] 2021-03-24 21:11
Not working on PTB is known and duplicate of #548

**Closed by rauenzi** 2021-03-24 21:11 UTC
Labels: bug

**Comment by EmreTech** [comment] 2021-03-24 22:15
Ah okay. Guess I'll wait for that to be fixed.
