### ISSUE TITLE
[Bug] BD not launching with discord.

### ISSUE THREAD

**Issue by USMCLivesOn** [rauenzi/BetterDiscordApp#686] opened 2021-04-11 09:39 UTC
I just updated discord and BD didnt launch with it. I reinstalled BD at least 3 times and its still not working.

![image](https://user-images.githubusercontent.com/76797453/114299249-42178700-9a88-11eb-9053-da7fbb852d8f.png)

**Comment by C0D3-M4513R** [comment] 2021-04-12 07:28
Duplicate of #685 & #688 ?

**Closed** 2021-04-16 22:51 UTC
Labels: bug
