### ISSUE TITLE
Doesn't auto login

### ISSUE THREAD

**Issue by SonOfDiablo** [rauenzi/BetterDiscordApp#145] opened 2019-02-14 09:40 UTC
After installing BBD, Discord no longer logs in automatically when it starts up.
I have tried removing BBD and then it works fine again.
I have even tried with a fresh windows installation (unrelated reasons), but BBD seems to interfere with something upon Discord starting up.

Is there something I'm missing? A setting maybe? Or is it just the price to pay for using BBD?

**Comment by Inve1951** [comment] 2019-02-14 09:44
That should only happen when you don't cleanly quit discord.

**Comment by SonOfDiablo** [comment] 2019-02-14 09:48
> That should only happen when you don't cleanly quit discord.

So this will happen if I shut down my PC without first closing Discord?

**Comment by Inve1951** [comment] 2019-02-14 10:07
Correct. AFAIK everyone has that issue, not just BD users.

**Comment by SonOfDiablo** [comment] 2019-02-14 10:09
@Inve1951 interesting, I haven't had that issue before I installed BBD...

I do however thank you for the info! Now I hopefully don't have to login to Discord manually every morning.

**Comment by PrinceDrew** [comment] 2019-02-15 04:09
This is definitely something that is happening recently. Don't know if Discord updated something, but default discord works as intended, remembering my account even without a "clean" close of the program prior to restarting computer. Once I install BBD this problem arises.

**Comment by intrnl** [comment] 2019-02-15 04:40
Duplicate of #143, #135, #137

This also happens on other client mods as well, it's Discord's problem, really.

**Closed** 2019-03-07 20:41 UTC
