### ISSUE TITLE
[Bug] First time I downloaded BetterDiscord, I went to settings and clicked 'Colored Text'. It worked the first time and I went ahead to get a theme after. I believe I installed BetterDiscord again and when I clicked 'Colored Text' again for the second time, the color never appeared. I uninstalled BetterDiscord and downloaded it again, but it never worked. I also tried repairing it, and it still didn't work. 

### ISSUE THREAD

**Issue by teixeira4** [rauenzi/BetterDiscordApp#566] opened 2021-03-03 11:33 UTC
**Describe the Bug**

**To Reproduce**

**Expected Behavior**

**Screenshots**
![#discussion - Discord 03_03_2021 11_26_57 (2)](https://user-images.githubusercontent.com/79976991/109799684-38426e80-7c14-11eb-8d20-8f2e0c835483.png)
![#discussion - Discord 03_03_2021 11_29_27 (2)](https://user-images.githubusercontent.com/79976991/109800355-f7972500-7c14-11eb-8232-d18bb4c34db4.png)

**Discord Version**

**Additional Context**

**Comment by rikusen0335** [comment] 2021-03-05 06:40
Please set a title for short, and write description in "Describe the Bug" section.
Also write "To Reproduce", because no one read long text

**Comment by rauenzi** [comment] 2021-03-24 21:17
Fixed by #573

**Closed by rauenzi** 2021-03-24 21:17 UTC
Labels: bug
