### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by xenovera** [rauenzi/BetterDiscordApp#480] opened 2020-10-30 23:42 UTC
better discord crashes as soon as i enable a plugin i recreate it every time i fix better discord to get it it even launch i have to repair it for every issue which makes no sense i have to reinstall it every time this happens and its as soon as i enable plugins or go to dm's  and i find it strange how its happening because their was nothing leading up to it happening that i can see that would cause it

**Comment by rauenzi** [comment] 2020-10-31 00:11
It sounds like you have some broken plugins. I know some plugins by DevilBro like GoogleTranslateOption are broken and will be fixed soon. I recommend _not_ enabling them. Wait for the developer to fix those. You can check console for errors to confirm.

**Comment by databoose** [comment] 2020-10-31 00:39
> It sounds like you have some broken plugins. I know some plugins by DevilBro like GoogleTranslateOption are broken and will be fixed soon. I recommend _not_ enabling them. Wait for the developer to fix those. You can check console for errors to confirm.

I know this is kind of offtopic, but for future instances in which a plugin is causing the issue, it'd be nice to see "Possibly caused by : (plugin here)" on the crash screen with the error, that way users could maybe better distinguish whether it's an issue with betterdiscord itself or just a plugin.

**Comment by Tropix126** [comment] 2020-11-01 23:34
> I know this is kind of offtopic, but for future instances in which a plugin is causing the issue, it'd be nice to see "Possibly caused by : (plugin here)" in red text on the crash screen with the error, that way users could maybe better distinguish whether it's an issue with betterdiscord itself or just a plugin.
> 
> Not sure if this is possible or not or how the logging system works, but just an idea i thought of.

#482 might also be a good idea.

**Closed** 2020-11-05 08:25 UTC
Labels: bug
