### ISSUE TITLE
Discord crashes upon hovering over the Mute, Deafen, and User Settings buttons

### ISSUE THREAD

**Issue by JG-GIT** [rauenzi/BetterDiscordApp#159] opened 2019-04-17 22:44 UTC
I don't know why this happens, but it just does.

**Comment by intrnl** [comment] 2019-04-17 22:46
We can't reproduce without more details.

Does the window just closes or does it just shows a crash screen?

If it shows a crash screen, don't reload or close it. Press Ctrl + Shift + I and head to the Console tab, then screenshot the errors, those are usually highlighted with red.

**Comment by Zmxhawrhbg** [comment] 2019-04-18 04:24
Hi, just throwing in there that this happens to me too, it shows a crash screen.
![image](https://user-images.githubusercontent.com/25387744/56336858-e941dc00-6156-11e9-8d2b-69c51918ba5b.png)
On Discord Canary.

**Comment by intrnl** [comment] 2019-04-18 05:20
Reproduced, here's the nitty gritty.

Discord somehow complains if the layerContainer class is modified, class normalizer needs to ignore it.

**Comment by Chazza** [comment] 2019-04-18 14:37
Yeah I am experiencing this as well..

**Closed** 2019-04-18 14:45 UTC

**Comment by JG-GIT** [comment] 2019-04-19 18:42
Alright, now it works.
