### ISSUE TITLE
[Bug] Doesn't work on latest version

### ISSUE THREAD

**Issue by SmanS723** [rauenzi/BetterDiscordApp#421] opened 2020-08-07 22:23 UTC
**Describe the Bug**
BD doesn't work anymore lol

**To Reproduce**
- Update Discord
- BD doesn't work now

**Expected Behavior**
BD Working

**Discord Version**
Stable

**Additional Context**
idk doesn't work on Linux for me

**Comment by saitama42069** [comment] 2020-08-08 03:49
Failed to install to /Applications/Discord.app: Missing file: ./app/betterdiscord/utils.js! -- Please retry install.

got this on macos mojave latest discord (0.0.258)

**Comment by shinji257** [comment] 2020-08-08 18:28
Broken on Windows here.
```
Starting installation for Discord
Killing Discord Processes
Downloading BandagedBD package
Finished downloading BandagedBD package
Extracting BandagedBD package
Renaming package dir
Deleting temp file C:\Users\shinj\AppData\Local\Discord\app-0.0.307\\resources\BetterDiscord.zip
Verifying installation
Checking for old style injection
C:\Users\shinj\AppData\Local\Discord\app-0.0.307\\resources\app\betterdiscord\utils.js does not exist! Verification failed!
```

**Comment by shinji257** [comment] 2020-08-08 18:33
Sorry.  This is a duplicate of #420 
With that said fix is to get the updated version of the installer from other repository by this author here...
https://github.com/rauenzi/BBDInstaller/

**Comment by PaoloTorregroza** [comment] 2020-08-08 19:21
I do te following and I still having the problem.

Update discord downloading the .deb from the discord downloads page
``sudo apt install ./discord.deb``

BD not working

``betterdiscordctl install``
``betterdiscordctl update``
``betterdiscordctl upgrade``

And not working :/

(I leave this here, maybe someone can found it usefull)

**Comment by PaoloTorregroza** [comment] 2020-08-08 19:23
Weird, After made tha things I say I made in the las comment and restart mi laptop it is working now

**Comment by Exitiumundos** [comment] 2020-08-08 19:58
For those using betterdiscordctl:

>betterdiscordctl install -b /usr/lib/betterdiscord-rauenzi-git
>betterdiscordctl reinstall
>betterdiscordctl update
>betterdiscordctl status

If it has injected properly you should see the location of the linked injector repository .
This is what i did to fix mine, you may need to do after each update. sometimes you wont need to do this.

**Comment by rauenzi** [comment] 2020-08-08 20:48
@SmanS723 You can follow the instructions above to try and reinject. However if you still have injection failures I recommend reaching out to those that actually make the linux installer. https://github.com/bb010g/betterdiscordctl

**Closed by rauenzi** 2020-08-08 20:48 UTC
Labels: bug
