### ISSUE TITLE
[Bug] BetterDiscord not working with Discord PTB

### ISSUE THREAD

**Issue by TheBeast941** [rauenzi/BetterDiscordApp#563] opened 2021-02-27 14:03 UTC
**Describe the Bug**
BetterDiscord does not launch with Discord PTB and on top of that the app works as if it is the website version of Discord (ie with no draggable window bar or the top banner with a button to "download" discord), also there is a space with another dividor which is where the BD settings should have been

**To Reproduce**
Simply launch Discord PTB for the first time after updating Discord

**Expected Behavior**
Discord should launch with BetterDiscord as expected, with your theme(s) being applied and all enabled plugins being loaded

**Screenshots**
![discord](https://user-images.githubusercontent.com/47040524/109389251-be547180-7903-11eb-813e-905c80258fb5.png)
No draggable bar present

![discord1](https://user-images.githubusercontent.com/47040524/109389334-0ecbcf00-7904-11eb-8ed4-0a1e311ca012.png)
BD dividor without settings

**Discord Version**
Ptb 77962 (c886d3c)

**Comment by Curtis-D** [comment] 2021-02-27 14:17
#561

**Comment by rauenzi** [comment] 2021-02-27 19:29
This is a duplicate of #548

**Closed by rauenzi** 2021-02-27 19:29 UTC
Labels: bug
