### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ArdynBlake** [rauenzi/BetterDiscordApp#685] opened 2021-04-11 09:30 UTC
![image](https://user-images.githubusercontent.com/82282299/114298989-f0cfbd80-9ab0-11eb-93be-3d637a4ac768.png)
Where all the other tabs used to be under BetterDiscord settings, there is now just settings with no way to access my plugins or themes folders. My plugins and themes also do not work within this update.

**Comment by C0D3-M4513R** [comment] 2021-04-12 07:27
Duplicate of #685 & #688 ?

**Comment by ArdynBlake** [comment] 2021-04-12 08:50
> Duplicate of #685 & #688 ?

#685 is the bug I reported, and unlike in #688 I can still run Discord without it crashing, it’s just the menus, plugins, and themes, (these being the only things I use) that aren’t working. I’ve found that using the discontinued installer works, and will continue to use the discontinued installer until this new and updated installer is patched

**Comment by C0D3-M4513R** [comment] 2021-04-12 21:00
sorry mistyped. meant #686

**Comment by rauenzi** [comment] 2021-04-16 22:51
Please reinstall BD, this should be fixed.

**Closed** 2021-04-20 04:41 UTC
Labels: awaiting response, bug
