### ISSUE TITLE
bd doesnt work when i install it and discord even thinks that the discord client is just a web browser i think its cus the client is outdated cus on a older version it worked fine [Bug]

### ISSUE THREAD

**Issue by xmootje015X** [rauenzi/BetterDiscordApp#591] opened 2021-03-18 16:17 UTC
**Describe the Bug**

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Discord Version**

**Additional Context**

**Comment by Tropix126** [comment] 2021-03-18 16:19
Please fill out the issue report correctly, though this is likely a duplicate of #585 #587 #548 #579 #577 #565 #563 #561 #551 and #589.

**Closed** 2021-03-18 16:45 UTC
Labels: bug
