### ISSUE TITLE
New Installer Stuck

### ISSUE THREAD

**Issue by somerandomuser1** [rauenzi/BetterDiscordApp#76] opened 2018-10-19 22:04 UTC
Title.

New installer just keeps getting stuck at "old injector detected"

**Comment by mrwallace888** [comment] 2018-10-19 22:08
Same. But when I exited and tried again, now no matter what I get this error:
Searching for Discord core in: C:\Users\miste\AppData\Roaming\Discord\0.0.301\modules\discord_desktop_core
core.asar does not exist in: C:\Users\miste\AppData\Roaming\Discord\0.0.301\modules\discord_desktop_core!
Unable to continue installation.

**Comment by rauenzi** [comment] 2018-10-20 03:19
For OP try running the installer as admin via right click.

Wallace, you're using an old installer

**Comment by Kallyopae** [comment] 2018-10-20 14:56
> Title.
> 
> New installer just keeps getting stuck at "old injector detected"

It does that because the injection method have been changed. Closing the installer after this error and starting it again will fix the issue, as when the error message appear, old files are deleted so starting the installer again will work as intended.

**Closed** 2018-10-20 19:40 UTC
