### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by McCrackles** [rauenzi/BetterDiscordApp#688] opened 2021-04-11 11:36 UTC
BD Won't launch with discord and bricks the program window as well making it unable to close, minimise or change and/or move the window.
![Screenshot 2021-04-11 133530](https://user-images.githubusercontent.com/82317458/114302769-cee33480-9aca-11eb-964b-92088801565b.png)

![Screenshot 2021-04-11 133425](https://user-images.githubusercontent.com/82317458/114302740-ace9b200-9aca-11eb-91ef-1f288e9ce810.png)

**Comment by QuatschFisch** [comment] 2021-04-11 11:50
Use the [Beta Installer](https://github.com/BetterDiscord/Installer/releases):

https://github.com/BetterDiscord/Installer/releases

**Comment by C0D3-M4513R** [comment] 2021-04-12 07:27
Duplicate of #685 & #686 ?

**Closed** 2021-04-16 22:51 UTC
Labels: bug
