### ISSUE TITLE
[Bug] New version Feels sluggish

### ISSUE THREAD

**Issue by TRaSH-** [rauenzi/BetterDiscordApp#683] opened 2021-04-10 22:35 UTC
**Describe the Bug**
New version Feels sluggish

**To Reproduce**
just use it for a while and you notice it get's sluggish

**Expected Behavior**
the old bandageBD was as snappy as without using a add-on, so i expect a new version doesn't impact the performance

**Discord Version**
OS: Windows 10
Discord Version: Stable

**Additional Context**
The old version BandageBD installer doesn't work anymore, the new one does but after some while of usage it's getting to slow, when typing and you want to remove a few words you have a big delay, when you paste a screenshot or something on a server its just slow

**Comment by rauenzi** [comment] 2021-04-10 22:45
This is a duplicate of #673 

Please respond to the comment there https://github.com/rauenzi/BetterDiscordApp/issues/673#issuecomment-816792981

**Closed by rauenzi** 2021-04-10 22:45 UTC
Labels: bug
