### ISSUE TITLE
BetterDiscord on Discord Development

### ISSUE THREAD

**Issue by IlCanePerIlGatto** [rauenzi/BetterDiscordApp#657] opened 2021-04-05 18:09 UTC
**Is your feature request related to a problem? Please describe.**
 I have Discord Development and I want to enjoy discord with BetterDiscord on the latest build but there is no option to use BetterDiscord on it.

**Describe the feature you'd like**
 I want it to be a feature please make it a feature thanks

**Comment by rauenzi** [comment] 2021-04-05 18:09
Duplicate of #520

**Closed by rauenzi** 2021-04-05 18:09 UTC
Labels: enhancement
