### ISSUE TITLE
[Bug] Crashes when using shift enter or creating a new line in channel text box

### ISSUE THREAD

**Issue by MMJv3** [rauenzi/BetterDiscordApp#571] opened 2021-03-05 19:55 UTC
**Describe the Bug**

creating a new line from too many characters or using shift enter to create a new line will crash the app

**To Reproduce**

sue enough characters to create a new line or press shift enter

**Expected Behavior**

the client wouldn't crash and a new line would be created

**Screenshots**

N/A

**Discord Version**

Stable

**Additional Context**

Tested with someone on stable non-BD and they didn't crash, all BD users crashed however

**Comment by Inve1951** [comment] 2021-03-05 19:56
reinstall BD

**Comment by Tropix126** [comment] 2021-03-05 20:05
duplicate of #568 and already fixed

**Comment by rauenzi** [comment] 2021-03-24 21:15
See above

**Closed by rauenzi** 2021-03-24 21:15 UTC
Labels: bug
