### ISSUE TITLE
[Feature] Keyboard shortcut deactivating all Better Discord's features

### ISSUE THREAD

**Issue by Sayrix** [rauenzi/BetterDiscordApp#822] opened 2021-06-03 19:29 UTC
A mode that disables all better discord plugins with a keyboard shortcut and reactivates them when you press the claver shortcut again, so that you can take screenshots without people realizing that you are using BetterDiscord

**Comment by rauenzi** [comment] 2021-06-05 17:50
Duplicate of #518

**Closed by rauenzi** 2021-06-05 17:50 UTC
Labels: enhancement
