### ISSUE TITLE
[Feature] support for Discord Developer

### ISSUE THREAD

**Issue by Methosss** [rauenzi/BetterDiscordApp#843] opened 2021-06-20 16:08 UTC
**Is your feature request related to a problem? Please describe.**

i have problem with installing it for discord development edition
**Describe the feature you'd like**

4'th option in installer
**Additional context**

![obraz](https://user-images.githubusercontent.com/32804020/122681018-9199d200-d1f2-11eb-96e9-967ea6d7a4d8.png)

**Comment by geshii** [comment] 2021-06-21 06:44
@Methosss did you try to install it manually ?
I don't know if adding it to the .exe Installer (I think you mean the .exe one) is a good idea since this client is just a canary clone and is deprecated.

**Comment by DonJTru** [comment] 2021-06-23 19:40
Discord Dev is the same as Canary with a few extra feats, by modifying one line of code in the `./scripts/inject.js` to contain the following line:
`const release = releaseInput === "canary" ? "Discord Canary" : releaseInput === "dev" ? "DiscordDevelopment" : releaseInput === "ptb" ? "Discord PTB" : "Discord";` Instead of `const release = releaseInput === "canary" ? "Discord Canary" : releaseInput === "ptb" ? "Discord PTB" : "Discord";` then running the command "npm run inject dev" this will work.

**Comment by rauenzi** [comment] 2021-07-02 03:54
Duplicate of #520

**Closed by rauenzi** 2021-07-02 03:54 UTC
Labels: enhancement
