### ISSUE TITLE
[Bug] I cant install BetterDiscord

### ISSUE THREAD

**Issue by EndzOnGit** [rauenzi/BetterDiscordApp#610] opened 2021-03-27 14:18 UTC
Failed to uninstall from : ReferenceError: Cannot access 'fs' before initialization

**Screenshots**
https://gyazo.com/2b55366ea7d5f43043f3b193df68ae23

**Discord Version**
Stable

**Additional Context**
i cant install bd

**Comment by 1Yanik3** [comment] 2021-03-27 18:56
same for me

**Comment by Tropix126** [comment] 2021-03-27 19:00
Duplicate of #600.

**Comment by ProofHF** [comment] 2021-03-28 13:33
Same issue, tried the manual injector as well-- can get discord to launch, but the BetterDiscord settings section is missing under settings. For some reason adding the app folder into resources on Mac causes you to lose further ability to close the app without a force quit. 

Hopefully this will get resolved soon.

**Comment by LoganDark** [comment] 2021-03-31 08:42
You're using an old version of the installer. As in, two releases out of date. However, the newest current release, while it installs correctly, will not create a working BBD installation because:

> Discord's new update breaks BBD because it relied on insecure features that Discord has now disabled. The `restructure` branch contains a version that works for new Discord, but it hasn't been officially released yet.

Once the new-new installer is released, you should be able to get BetterDiscord again. That is the version that will install the restructured version.

**Comment by rauenzi** [comment] 2021-03-31 21:13
Try to install BetterDiscord using this new beta installer: https://github.com/BetterDiscord/Installer

**Closed by rauenzi** 2021-03-31 21:13 UTC
Labels: bug
