### ISSUE TITLE
[Bug] Loading error of discord user streaming

### ISSUE THREAD

**Issue by eeemmmddd** [rauenzi/BetterDiscordApp#423] opened 2020-08-09 09:09 UTC
**Describe the Bug**

If you turn on the pop-up window of Discord and try to watch the Discord member's own broadcast, the broadcast that appeared well will continue to load in the pop-up window. I tried removing betterdiscord to see if this was a problem with betterdiscord and only then this function worked fine.
**To Reproduce**

**Expected Behavior**

**Screenshots**

![제목 없음](https://user-images.githubusercontent.com/69417338/89728829-1bbdc980-da6b-11ea-8708-f4062f82cf38.png)

**Discord Version**

Stable 64952 (f65e21b)
BBD 0.3.5
Host 0.0.307
Injector 0.6.2
Windows 10 64-Bit (10.0.18363)
**Additional Context**

**Comment by MistressAshai** [comment] 2020-08-13 16:22
I'm also getting this issue.

Stable 65193 (1fb5179)
BBD 0.3.5
Host 0.0.307
Injector 0.6.2
Windows 10 64-Bit (10.0.18362)

**Comment by rauenzi** [comment] 2020-08-15 04:45
This is a duplicate of #417

**Closed by rauenzi** 2020-08-15 04:45 UTC
Labels: bug
