### ISSUE TITLE
[Bug] Update Message showing on every boot.

### ISSUE THREAD

**Issue by PassiveModding** [rauenzi/BetterDiscordApp#193] opened 2019-05-29 05:11 UTC
**Describe the Bug**
https://github.com/rauenzi/BetterDiscordApp/commit/52f538169986cd3e84c074b086ecf26c1123a365 updates the latest version to 0.3.2 which is greater than the latest released version. This causes the update message to show every time discord is opened with no method of disabling it.

**Comment by rauenzi** [comment] 2019-05-29 05:13
Duplicate of the pinned issue #191 please read my comments there.

**Closed by rauenzi** 2019-05-29 05:13 UTC
Labels: bug
