### ISSUE TITLE
[Bug] after new update the extension doesn't work anymore

### ISSUE THREAD

**Issue by XxMrFiresxX** [rauenzi/BetterDiscordApp#311] opened 2020-02-27 12:18 UTC
after the auto update for discord the extension doesn't work anymore

**Comment by okami-x** [comment] 2020-02-27 17:34
If you mean that BetterDiscord is not working with the last update you should try to move the "app" folder located in C:\Users\%UserName%\AppData\Local\Discord\app-0.0.305\resources to  C:\Users\%UserName%\AppData\Local\Discord\app-0.0.306\resources

**Comment by XxMrFiresxX** [comment] 2020-02-27 17:35
oh i see will try and update you on it

**Comment by XxMrFiresxX** [comment] 2020-02-27 17:42
my app was located as roaming at the end

**Comment by rauenzi** [comment] 2020-02-27 17:45
Then you located the wrong folder. Just run the installer and install BD again. Duplicate of #310 #309

**Closed by rauenzi** 2020-02-27 17:45 UTC
Labels: bug
