### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by LonnonjamesD** [rauenzi/BetterDiscordApp#585] opened 2021-03-13 01:22 UTC
**Describe the Bug**
The bar that contains fullscreen and alt-f4 button are missing

**To Reproduce**
install Betterdiscord on PTB or Canary

**Expected Behavior**
It should still be there

**Screenshots**
![image](https://user-images.githubusercontent.com/55360995/111014204-a43d7900-8370-11eb-8007-84994f42e059.png)
![image](https://user-images.githubusercontent.com/55360995/111014220-bae3d000-8370-11eb-8655-b87ab8cfc38d.png)
![image](https://user-images.githubusercontent.com/55360995/111014236-c9ca8280-8370-11eb-9f73-7455474a025f.png)

**Discord Version**
Canary and PTB

**Additional Context**
this is a fresh install of canary

**Comment by Tropix126** [comment] 2021-03-13 01:38
This is a known issue and will be fixed soon.

**Comment by rauenzi** [comment] 2021-03-24 21:14
Duplicate of #548

**Closed by rauenzi** 2021-03-24 21:14 UTC
Labels: bug
