### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ICExFS** [rauenzi/BetterDiscordApp#578] opened 2021-03-09 08:41 UTC
When you use CTRL + V to paste it automatic-crash

Using discord stable

**Comment by ICExFS** [comment] 2021-03-09 08:42
I tried uninstalling, reinstalling but nothing worked

**Comment by i9bonsai** [comment] 2021-03-09 12:02
getting the same problem

**Comment by ND-64** [comment] 2021-03-10 09:40
I have the same issue, with just discord links.

**Comment by armoha** [comment] 2021-03-14 08:29
Maybe duplicate of #568, #571, or #575
Reinstalling BD fixed for me.

**Comment by TheTrueShadow** [comment] 2021-03-17 23:05
> When you use CTRL + V to paste it automatic-crash
> 
> Using discord stable

same issue but when I go onto a new line of text crash

**Comment by rauenzi** [comment] 2021-03-24 21:15
The issue is fixed by a reinstall when possible

**Closed by rauenzi** 2021-03-24 21:15 UTC
Labels: bug

**Comment by ICExFS** [comment] 2021-03-25 06:58
No, I tried uninstalling but it didn’t worked.



-- 
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus
