### ISSUE TITLE
Make App for Android and iOS

### ISSUE THREAD

**Issue by Minionguyjpro** [rauenzi/BetterDiscordApp#840] opened 2021-06-18 13:20 UTC
Make Betterdiscord app for Android and iOS if possible.

**Comment by boehs** [comment] 2021-06-23 14:40
Duplicate of #265, #184, #158
IOS is no, near impossible to distribute apps without the app store making the effort worthless.
You are likely looking for: https://gitdab.com/distok/cutthecord

**Comment by rauenzi** [comment] 2021-07-02 03:57
See above

**Closed by rauenzi** 2021-07-02 03:57 UTC
Labels: enhancement
