### ISSUE TITLE
[Documentation] Add a plugin development tutorial

### ISSUE THREAD

**Issue by YodaLightsabr** [rauenzi/BetterDiscordApp#525] opened 2021-01-03 17:30 UTC
As far as I can see, there is no documentation, guide, help page, or obvious starting point for creating plugins. If there is a link to a documentation or something, please send it.

**Comment by rauenzi** [comment] 2021-01-03 21:03
There is documentation available on the Wiki here on Github

**Comment by rauenzi** [comment] 2021-04-02 17:32
This is actually a duplicate of #405

**Closed by rauenzi** 2021-04-02 17:32 UTC
Labels: enhancement
