### ISSUE TITLE
 Custom CSS, themes, and plugins do not appear under discord settings [Bug]

### ISSUE THREAD

**Issue by vellaG** [rauenzi/BetterDiscordApp#669] opened 2021-04-08 11:57 UTC
**Describe the Bug**
Toggle Custom CSS, themes, and plugins do not appear under discord settings

**To Reproduce**
Simply doing a manual install results in the inability to edit custom css and access the plugins/themes tab.

**Expected Behavior**
Expected the ability to access the custom css tab from the settings page. Aswell as plugins and themes.

**Screenshots**

![image](https://user-images.githubusercontent.com/61596989/114022416-5ca6f180-9837-11eb-9c04-d1887c11efc3.png)
![image](https://user-images.githubusercontent.com/61596989/114022581-8829dc00-9837-11eb-9ebc-7cf3a7061b4a.png)

**Discord Version**
Stable Discord

**Comment by ramonGonzEdu** [comment] 2021-04-08 14:01
add some sort of title that isnt just [Bug] so that people can tell what the issue is about at a glance

**Comment by ZaPeZaPe** [comment] 2021-04-08 17:24
Its happening with me too

**Comment by vellaG** [comment] 2021-04-08 21:34
I went to a server and it loaded in for some reason. Try that.

**Comment by ZaPeZaPe** [comment] 2021-04-08 21:38
> I went to a server and it loaded in for some reason. Try that.

got it

**Comment by rauenzi** [comment] 2021-04-09 16:15
Close discord, rename your BetterDiscord folder (to backup the files), and reinstall.

**Comment by rauenzi** [comment] 2021-04-10 22:24
After re-reading I see this bug is actually a duplicate of #627 and will be fixed in the next update

**Closed by rauenzi** 2021-04-10 22:24 UTC
Labels: awaiting response, bug, needs info
