### ISSUE TITLE
Discord will not remember credentials

### ISSUE THREAD

**Issue by discordissues123995** [rauenzi/BetterDiscordApp#137] opened 2019-01-17 15:18 UTC
As of right now, using BandagedBD requires you to enter your credentials every time you open Discord. I have tried toggling 2FA and Dev Mode but nothing seems to be working. It seems as though you can close the app and reopen it, but restarting the computer will make Discord ask for credentials.

**Comment by intrnl** [comment] 2019-01-17 15:41
Still have no idea why this happens unless you close Discord with devtools opened, since Discord hides the token from local storage and won't put it back in until you close devtools.

**Comment by discordissues123995** [comment] 2019-01-17 15:53
By devtools you mean Developer mode under "Core" right? If so, that is always turned off. I tried giving Discord admin by default when it opens and no change there either. Just to reiterate closing down discord and opening it = no problem. Restarting computer = problem.

**Comment by intrnl** [comment] 2019-01-17 15:55
nope, Ctrl + Shift + I, Chrome developer tools.

From the sound of it, you probably don't have it opened.

**Comment by discordissues123995** [comment] 2019-01-17 15:56
Correct. I do not use that.

**Comment by rauenzi** [comment] 2019-01-17 16:55
This is a duplicate of #135 

This is an issue with Discord's token hiding logic which they are aware of.

**Closed by rauenzi** 2019-01-17 16:55 UTC
