### ISSUE TITLE
[Bug] Multiple different things crash discord.

### ISSUE THREAD

**Issue by BoredFishRE** [rauenzi/BetterDiscordApp#541] opened 2021-01-20 18:19 UTC
I know, some are already there. But, I found another thing and some other weird things. A. The crash on Ctrl+V only happens occasionally, never consistent. B. Shift + Enter always happens with BD. C. Opening CSS editor crashes it. Could it be an issue with some CSS change for the new Discord Canary update? 

Computer Details:
Canary 74766 (1425870)
BBD 0.3.5
Host 1.0.17
Injector 0.6.2
Windows 10 64-Bit (10.0.19042)

**Comment by spont24** [comment] 2021-01-20 21:39
I'm also getting the exact same issues using the latest versions of Canary and BD, it started happening last night for me whenever I use CTRL+V and Shift+Enter, also happens when I try pasting with my mouse.

**Comment by PactoSac** [comment] 2021-01-20 21:51
It's also happening to me, if I write more than one line, or paste something, or press Shift+Enter, it crashes.

**Comment by Biozeminade** [comment] 2021-01-21 01:24
I can't even open Canary anymore. It just straight up crashes everytime I try and open it. Thankfully, the normal client appears to be working fine, although I would still like to return to Canary sometime soon...

**Comment by rauenzi** [comment] 2021-01-21 06:37
For those having issues with Canary (including the shift+enter and pasting issues) please locate your BD installation (`C:\Users\<username>\AppData\Local\DiscordCanary\app-1.0.18\resources\app\betterdiscord`) and replace the `preload.js` with this one https://cdn.discordapp.com/attachments/174279718500171776/801689518570340372/preload.js

**Comment by firesage86** [comment] 2021-03-14 11:24
> 
> 
> It's also happening to me, if I write more than one line, or paste something, or press Shift+Enter, it crashes.

Same thing's happening to me as well, it crashes when I try to paste or Shift-Enter in chat.

**Comment by Biozeminade** [comment] 2021-03-15 01:51
Actually it doesn't even matter anymore. After over a month and a half now, Canary refuses to load anything from BetterDiscord, no matter how many times I uninstall and reinstall it. And on top of that, the window bar at the top that lets me close, resize and minimize the window is gone. A friend using PTB also claims it's starting to fail so we both are now forced to use the standard client which still works. We suspect that an update in Chromium is the perpetrator.

And before you ask, no replacing the preload.js file did nothing.

**Comment by rauenzi** [comment] 2021-03-24 21:21
This is duplicate of #548 / #442

**Closed by rauenzi** 2021-03-24 21:21 UTC
Labels: bug
