### ISSUE TITLE
[Bug] Cannot Open after installing on Discord Canary

### ISSUE THREAD

**Issue by Copimox** [rauenzi/BetterDiscordApp#858] opened 2021-06-30 19:49 UTC
**Description**
After installing BetterDiscord on Canary, I get this error message:
![image](https://user-images.githubusercontent.com/81705406/124022101-5d749d00-d9ba-11eb-8064-c830eebdf1a0.png)

**To Reproduce**
1. Install Discord Canary
2. Download and install BD on Canary

**Expected Behaviour**
BetterDiscord running on Discord Canary

**Screenshots**
Located Above

**Discord Version**
Canary  (The latest I guess, fresh install just before this issue)

**Additional Context**
I just converted to Canary now this
really annoying

**Comment by Copimox** [comment] 2021-06-30 19:50
One more thing I forgot: Repairing doesnt work

**Comment by nchristopher** [comment] 2021-06-30 23:17
This is a known issue, see #821.
> Discord's latest update includes pushing Electron 13, please be patient while fixes are made. In the meantime use stable or just uninstall BD on Canary.

**Comment by dav1312** [comment] 2021-07-01 10:42
Duplicate of #821

**Closed** 2021-07-01 12:27 UTC
Labels: bug
