### ISSUE TITLE
Installer Window not scaling properly [Bug]

### ISSUE THREAD

**Issue by hacksncode** [rauenzi/BetterDiscordApp#262] opened 2019-10-19 20:26 UTC
**Describe the Bug**
Self explanatory, basically you can't choose a version you want to install BD into

**To Reproduce**
open program on my friends pc

**Expected Behavior**
Normal scaling

**Screenshots**
https://imgur.com/XhYGpj5

**Discord Version**
Stable

**Additional Context**

**Comment by Mattlau04** [comment] 2019-10-31 20:30
i got the same bug, it was because of MSI scalling

**Comment by BbaassTMH** [comment] 2019-11-13 09:50
Having this issue aswell.
Managed to work around it by first changing the scaling (Control Panel\All Control Panel Items\Display) to "Smaller - 100%", signing out and back in to actually apply it, running the installer as intended, then changing the scaling back to "Medium - 125% (default)" and signing out and back in again.

Running Win8.1.

**Comment by rauenzi** [comment] 2019-11-19 16:48
Yep it's due to scaling, duplicate of https://github.com/rauenzi/BBDInstaller/issues/5

**Closed by rauenzi** 2019-11-19 16:48 UTC
Labels: bug
