### ISSUE TITLE
[Bug] crash at startup after injecting from source

### ISSUE THREAD

**Issue by spiralw** [rauenzi/BetterDiscordApp#791] opened 2021-05-19 19:42 UTC
**Describe the Bug**
Discord crashes with JavaScript error "Session can only be received when app is ready" after injecting.

**To Reproduce**
Follow steps in README under "Manual installation"

**Expected Behavior**
Discord starts correctly.

**Screenshots**
Screenshot wouldn't be helpful, but here's the traceback:
```
spiral@computer:~/BetterDiscordApp$ discord
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Session can only be received when app is ready
    at Object.get [as defaultSession] (electron/js2c/browser_init.js:117:366)
    at Function.remove (webpack-internal:///./src/modules/csp.js:11:64)
    at eval (webpack-internal:///./src/index.js:34:60)
    at Object../src/index.js (/home/spiral/BetterDiscordApp/dist/injector.js:29:1)
    at __webpack_require__ (/home/spiral/BetterDiscordApp/dist/injector.js:142:41)
    at /home/spiral/BetterDiscordApp/dist/injector.js:194:37
    at Object.<anonymous> (/home/spiral/BetterDiscordApp/dist/injector.js:196:12)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
```

**Discord Version**
Stable

**Additional Context**
Linux Mint 20.1

**Comment by Tropix126** [comment] 2021-05-24 03:51
Are you using a snap or flatpak install?

**Comment by spiralw** [comment] 2021-05-24 11:07
No, I'm using the source installation.

**Comment by rauenzi** [comment] 2021-06-05 17:48
That's not what Tropix meant, but this is a duplicate of #789 please see my comment there

**Closed by rauenzi** 2021-06-05 17:48 UTC
Labels: bug

**Comment by spiralw** [comment] 2021-06-05 18:49
What did Tropix mean then? I didn't use snap or flatpak, I cloned the git repo and installed and ran the injector from there.
anyway, thanks for pointing me to the correct issue :)
