### ISSUE TITLE
[Feature] Toggle whether or not Plugins/Themes will load

### ISSUE THREAD

**Issue by PaxiTheAlchemist** [rauenzi/BetterDiscordApp#505] opened 2020-11-16 18:53 UTC
# [Feature] Toggle whether or not Plugins/Themes will load

## My Pitch

Let's say you are running a system-intensive application, yet, you do not want to close discord. Depending on how many plugins a user may have or how element heavy a custom theme may be, keeping Discord open may drastically impact the overall performance of your system or said application. A way to tackle this would be a way to toggle whether or not Better Discord will load plugins and themes either through a switch/checkbox or a way to restart discord in a "safe mode" (like some applications do), and vice versa

## The Feature

As said above, I would like to suggest a way for Better Discord to toggle whether or not plugins and or themes will load. This being either through a toggle button or check box. I am taking into account that disabling things while they are running can possibly cause issues. With this, in mind, an alternative way of implementing this could be through the use of a button that can relaunch discord (still injected) into a "safe mode" that disables those plugins and themes. In this "safe mode", the same button will still be available, however for reversing the "safe mode" and relaunching back into your previous setup.

## Additional context

Here is a mockup of the feature

![Mockup of requested Feature](https://i.imgur.com/ZxMsE5D.png)

*And also, if you are wondering, both methods of activating this feature are present within this mockup, the switch and the button. I did not represent the button to reverse the "safe mode", but that should be self-explanatory*

**Comment by fullbyte1337** [comment] 2020-11-16 18:55
yes please! this would be really great IMO,

**Comment by rauenzi** [comment] 2020-11-16 19:10
I believe this is a duplicate of #482, please let me know if they are different.

**Comment by PaxiTheAlchemist** [comment] 2020-11-16 20:20
Yes, it is different. seems like the author of that issue seems to be having debugging issues, but yes, the purpose of my feature request is to lower the resource usage of better discord, not for debugging, however ill gladly include that use for my feature into my request due to the helpfulness it can provide in fixing bugs and developing.

**Comment by PaxiTheAlchemist** [comment] 2020-11-16 20:39
Actually, i take that back. The part where i mention the "safe mode", where the client restarts without plugins and themes, is a duplicate of that issue you mentioned. However, i did mention another method of implementation that involves a switch instead of an outright button which restarts the client. A method in which discord can simply disable all plugins and themes without the need of restarting the client (with the possibilities of breaking things considering the fact that plugins will be disabled while they are running. i am unsure whether or not this may actually pose an issue, however, its something to keep in mind)

**Comment by rauenzi** [comment] 2021-01-12 19:50
> However, i did mention another method of implementation that involves a switch instead of an outright button which restarts the client

Though I do appreciate the mockup, this is not a significantly different enough piece to keep it in a separate issue. I'll be closing this as a duplicate of #482 for ease of tracking this in the future

**Closed by rauenzi** 2021-01-12 19:50 UTC
Labels: enhancement
