### ISSUE TITLE
[Bug] No longer working after restart, "continuously failed to update"

### ISSUE THREAD

**Issue by camdenorrb** [rauenzi/BetterDiscordApp#562] opened 2021-02-27 03:13 UTC
**Describe the Bug**
Discord no longer loads, says it failed to update

**To Reproduce**
Install betterdiscord on latest stable apparently

**Screenshots**
![image](https://user-images.githubusercontent.com/5360339/109373906-3fb1f280-7877-11eb-8a53-09b6b8d220a1.png)

**Discord Version**
Stable
![image](https://user-images.githubusercontent.com/5360339/109373932-5e17ee00-7877-11eb-9fe9-6d3748aa239a.png)

**Additional Context**
It was working for months before my latest restart.

After reinstalling discord and deleting the Discord folder, it loads up, but after installing betterdiscord it gives me that error now.

**Comment by Curtis-D** [comment] 2021-02-27 14:16
Could possibly be related to #561?

**Comment by rauenzi** [comment] 2021-02-27 19:28
It's possible the changes from #548 have made it's way into stable on linux but not other platforms. Can you open console and look for errors?

**Comment by arpit-saxena** [comment] 2021-02-28 14:27
I'm getting the same issue. I use https://github.com/bb010g/betterdiscordctl for managing BetterDiscord, so it might be a problem from there. See the following screenshot of the errors in the console.
![image](https://user-images.githubusercontent.com/14573995/109421860-1fad3b00-79ff-11eb-8dd0-e5b9da5c53cb.png)

**Comment by camdenorrb** [comment] 2021-02-28 18:12
I also use betterdiscordctl and am getting the same error as @arpit-saxena

![image](https://user-images.githubusercontent.com/5360339/109428737-0afc8300-79be-11eb-8dd4-01f9f19becd7.png)

**Comment by rauenzi** [comment] 2021-03-24 21:17
This is duplicate of #548 / #442

**Closed by rauenzi** 2021-03-24 21:17 UTC
Labels: bug
