### ISSUE TITLE
BetterDiscord Canary crashes upon open on Ma

### ISSUE THREAD

**Issue by DefaultAnimator** [rauenzi/BetterDiscordApp#852] opened 2021-06-28 15:43 UTC
When I try to launch Betterdiscord on Canary Mac, it comes up with this error message:
Uncaught Exception:
TypeError: process.electronBinding is not a function
    at /Users/(My user)/Library/Application Support/BetterDiscord/data/betterdiscord.asar/injector.js:1:5940
    at Object.<anonymous> (/Users/(My user)/Library/Application Support/BetterDiscord/data/betterdiscord.asar/injector.js:1:6951)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Applications/Discord Canary.app/Contents/Resources/app/index.js:1:1)

**Comment by SebiTalent04** [comment] 2021-06-29 11:22
Check #821.

**Comment by dav1312** [comment] 2021-07-01 10:42
Duplicate of #821

**Comment by rauenzi** [comment] 2021-07-02 03:56
See above

**Closed by rauenzi** 2021-07-02 03:56 UTC
