### ISSUE TITLE
[Bug] BD Crashes when writing on dm's,

### ISSUE THREAD

**Issue by DeQuex** [rauenzi/BetterDiscordApp#590] opened 2021-03-18 01:34 UTC
**Describe the Bug**
BD Crashes when writing on dm's, example: if I press Shift + Enter crashes

**Discord Version**
Stable

**Comment by Tropix126** [comment] 2021-03-18 02:26
Duplicate of #571 and #568 and also already fixed.
Reinject BD and it should work fine.

**Closed** 2021-03-18 16:45 UTC
Labels: bug
