### ISSUE TITLE
[Bug] Terrible performance/slowdowns while BD is installed

### ISSUE THREAD

**Issue by JonNobo** [rauenzi/BetterDiscordApp#740] opened 2021-04-28 21:56 UTC
I've been using BandagedBD for quite some time now, since the regular versions of BetterDiscord always seemed to have had really bad slow-downs & generally slowed down the entire program for me. I can't find anything about this, & since BandagedBD no longer seems to hook & isn't supported anymore, I may as well bring it up now.

This seems to be excessively noticeable when switching over to the settings tab; Almost the entire transition animation, even with minimal animations enabled, brings the entire program to a slideshow until it finishes the animation. Repeat when exiting the settings menus. Performance also seems to be haphazard when mousing over hoverable elements, but is slow or laggy in general. 

All of this happens on Stable, but I have not tried other versions of Discord yet.
I'm really not sure if it's just me, or some settings I do and/or don't have enabled, but I'm really hoping to get some feedback about this at the least.

**Comment by rauenzi** [comment] 2021-05-07 00:14
This seems to be a duplicate of #673

**Closed by rauenzi** 2021-05-07 00:14 UTC
Labels: bug
