### ISSUE TITLE
Click to update glitch

### ISSUE THREAD

**Issue by ForceLP** [rauenzi/BetterDiscordApp#456] opened 2020-09-24 15:10 UTC
![image](https://user-images.githubusercontent.com/69095006/94164003-cd348500-fe88-11ea-81d0-6bb55e06a6b7.png)

**Comment by rauenzi** [comment] 2020-09-24 15:24
Duplicate of #455 and #453 manually update ZeresPluginLibrary.

**Closed by rauenzi** 2020-09-24 15:24 UTC
