### ISSUE TITLE
Update prompt for ghost update[Bug]

### ISSUE THREAD

**Issue by Aida-Enna** [rauenzi/BetterDiscordApp#192] opened 2019-05-29 02:38 UTC
**Describe the Bug**
Prompted to update to 0.3.2, but there is no 0.3.2 update, just 0.3.1 from a while ago.

**To Reproduce**
Open discord.

**Screenshots**
![image](https://user-images.githubusercontent.com/5483362/58525327-68382480-8199-11e9-8541-90e144915872.png)

**Discord Version**
Stable

**Comment by rauenzi** [comment] 2019-05-29 02:50
duplicate of #191 please read the comments there

**Closed by rauenzi** 2019-05-29 02:50 UTC
Labels: bug
