### ISSUE TITLE
Canary Discord Imcompatible with BD.

### ISSUE THREAD

**Issue by JoeyDagger** [rauenzi/BetterDiscordApp#551] opened 2021-01-31 08:49 UTC
Putting in a repost of my own bug talking about how it doesn't work on Canary version of Discord. Only reposting since rauenzi is so fucking anal and an absolute smartass who doesn't want people talking on their own post and locked it. Post below if you have the issue as well because I allow it and if you have anything to add so the owner can maybe figure out where to start.

rauenzi acting like a child:
![image](https://user-images.githubusercontent.com/67937427/106375202-043b0b80-633f-11eb-8e0e-6bc97b1bee6a.png)
![image](https://user-images.githubusercontent.com/67937427/106375221-4401f300-633f-11eb-84b4-44183f4d6b2f.png)

Disclaimer, the post is already 'solved' since it was more of a question instead of a fixable thread. I know it's incompatible. I'm allowing people to confirm their problems and add onto the list so it's actually helpful to the petty coder. 

Original Post:
_"On the latest Canary version of Discord, every time I select install or repair on Canary and it runs through it's process, it has been completely unusable. I'm not sure what happened but it all started maybe during the last weekend if I remember correctly."_

_"There's multiple problems that this causes that makes it practically useless. The first few obviously noticeable problems I'm having is that the zoom is incredibly high and can't be changed and it has no bar at the top to close, maximize, or minimize. I am permanently muted and can't unmute myself. Going into settings shows that discord doesn't pick up any of my microphones or my camera. Not to mention none of my settings are able to be changed and do anything in reference to my audio or size. In the bottom images, it also shows that my discord is acting like it's open in a browser tab instead of the actual app which is absolutely unbelievable."_

_"When I try and join a call or server voice channel, I doesn't say I'm connected in the badge on my taskbar with the green circle. Not to mention I can hear them still, but still can't unmute or say anything. And on top of all that, in settings, it doesn't even show that BandadgedBD is even installed."_

_"Now despite all of this, regular discord surprisingly works just fine. Nothing has changed at all for it. I even tried uninstalling, ridding of all of my plugins and themes, etc. Doing the same for both has done nothing to fix Canary and regular Discord still works just like how it and Canary is supposed to."_
![image](https://user-images.githubusercontent.com/67937427/106375236-6ac02980-633f-11eb-8e63-db3537dfd079.png)
![image](https://user-images.githubusercontent.com/67937427/106375240-6dbb1a00-633f-11eb-9c74-039f083fd794.png)
![image](https://user-images.githubusercontent.com/67937427/106375241-701d7400-633f-11eb-94cf-290a929871de.png)
![image](https://user-images.githubusercontent.com/67937427/106375243-727fce00-633f-11eb-9f07-154575b041e5.png)
![image](https://user-images.githubusercontent.com/67937427/106375244-74e22800-633f-11eb-8163-66aa89a86991.png)
![image](https://user-images.githubusercontent.com/67937427/106375247-77448200-633f-11eb-98b4-23a7e9edae02.png)
![image](https://user-images.githubusercontent.com/67937427/106375249-7ad80900-633f-11eb-9a63-d9827d71420a.png)
![image](https://user-images.githubusercontent.com/67937427/106375251-7dd2f980-633f-11eb-8dea-f12470f2cc74.png)

**Comment by l0c4lh057** [comment] 2021-01-31 10:57
> since rauenzi is so fucking anal and an absolute smartass who doesn't want people talking on their own post and locked it

you mean bc nobody of you understands what github issues are for? they are not for spamming `same` and `also have this problem`.

> Post below if you have the issue as well

no, don't do that. there is no reason for you to do that. as zerebos said: [*Users are much better off indicating they face a similar issue by reacting with :+1: to the original issue post. They can also click the button on the right hand side if they wish to subscribe to the issue.*](https://github.com/rauenzi/BetterDiscordApp/issues/548#issuecomment-770303282)

> because I allow it

but you are not the one who gets to decide that. i can tell you that this issue will just get closed for being a duplicate. at least when people start commenting here that they also have the problem then it will get locked.

feel free to check what the issue is yourself and share the information you gather on where the issue is or maybe even how to maybe fix it. but don't just spam the notifications with useless messages. if you already know something is an issue then you dont need 100 more people telling you that it is an issue.

**Comment by rauenzi** [comment] 2021-01-31 15:01
Duplicate of #548

**Closed** 2021-01-31 15:01 UTC
Labels: bug

**Comment by Tropix126** [comment] 2021-02-01 01:50
Please bring this elsewhere. The entire purpose of this issue was to spite someone who puts their own free time into this project, and to add further fuel a mild argument. If that's all you came here to do, we don't want you as part of this community or contributing to this repo.

**Comment by JoeyDagger** [comment] 2021-02-01 02:22
Regardless of spite or not, nobody points out the fact that, even if said person may be putting their time into the project, is still an asshole.

**Comment by JoeyDagger** [comment] 2021-02-01 02:29
I came here to say there was an issue and point out what the issues were and went into detail on what was wrong. Meanwhile, rauenzi decided to be petty as fuck and lock the post because notifications bothered him that bad instead of wanting to listen to the community **using** his fucking program and the issues that go along with it, if anymore arose.

**Comment by rauenzi** [comment] 2021-02-01 03:48
I'm already aware of what the issues regarding BD and Canary are--they are due to the changes lined out in #442. I interact with and support the community a lot already through our Discord servers.

**Comment by Tropix126** [comment] 2021-02-01 17:53
> petty as fuck and lock the post because notifications bothered him that bad instead of wanting to listen to the community **using** his fucking program and the issues that go along with it, if anymore arose.

This issue isn't a simple one-line fix. It's a front to a much larger change, which is discord switching their electron version to their own fork of it. A fix for this issue will either require a large change in the core of how BD injects and runs, or a patch which will break plugins significantly. He didn't lock the issue because he didn't want to fix it. He locked the issue because he was a) already aware of the issue. b) discussion was getting offtopic from the actual bug being reported. This is something already known within the community. Opening up duplicate issues and then being angry when an issue is marked as a duplicate or closed simply doesn't make sense and isn't how github is meant to be used.

![image](https://user-images.githubusercontent.com/42101043/106497744-0c509380-6484-11eb-985b-b3af1183d50f.png)

**Comment by MasicoreLord** [comment] 2021-02-03 19:56
> > petty as fuck and lock the post because notifications bothered him that bad instead of wanting to listen to the community **using** his fucking program and the issues that go along with it, if anymore arose.
> 
> This issue isn't a simple one-line fix. It's a front to a much larger change, which is discord switching their electron version to their own fork of it. A fix for this issue will either require a large change in the core of how BD injects and runs, or a patch which will break plugins significantly. He didn't lock the issue because he didn't want to fix it. He locked the issue because he was a) already aware of the issue. b) discussion was getting offtopic from the actual bug being reported. This is something already known within the community. Opening up duplicate issues and then being angry when an issue is marked as a duplicate or closed simply doesn't make sense and isn't how github is meant to be used.
> 
> ![image](https://user-images.githubusercontent.com/42101043/106497744-0c509380-6484-11eb-985b-b3af1183d50f.png)

For the record, Discord has been using it's own electron build in regular discord bundles for a long time, at least all the way back to when they released v2 of their overlay, which the rendering for it is done through an off-screen window spawned by their electron process.
