### ISSUE TITLE
Install button dark blue will not install[Bug]

### ISSUE THREAD

**Issue by Mom-Kat** [rauenzi/BetterDiscordApp#250] opened 2019-09-17 16:15 UTC
**Describe the Bug**

It simply doesn't work. The Install button is darker blue than the others and does nothing.
**To Reproduce**

Downloaded installer.
Moved file to C:
Ran as Admin
Accepted agreement
Choose install
All installs show but the Install button is darker blue than the others and does nothing.
**Expected Behavior**

**Screenshots**

**Discord Version**

All, newly upddated

**Additional Context**

Win7 pro 64bit
![BBD](https://user-images.githubusercontent.com/32440184/65059903-d66d4680-d944-11e9-92ad-40acb032f87a.png)

**Comment by NFLD99** [comment] 2019-09-27 12:31
youll need to fix your dpi in windows settings
im not sure if its the same on win7 however the setting is this: 
![ApplicationFrameHost_2019-09-27_10-00-42](https://user-images.githubusercontent.com/24623601/65769267-c5bf8c00-e10d-11e9-97a9-b54f3bdb529a.png)

**Comment by neoarc** [comment] 2019-10-02 07:51
It's not dpi issue, "Install" button is disabled, so he can't click it.
same thing happened to me. :(

**Comment by rauenzi** [comment] 2019-10-02 11:48
No it's a dpi issue. The button becomes enabled when you click one of the checkboxes that are pushed off-screen in the first screenshot due to scaling.

**Comment by rauenzi** [comment] 2019-11-19 16:54
Duplicate of rauenzi/BBDInstaller#5

**Closed by rauenzi** 2019-11-19 16:54 UTC
Labels: bug
