### ISSUE TITLE
Can't install BBD on latest Discord Canary version.

### ISSUE THREAD

**Issue by xHeaveny** [rauenzi/BetterDiscordApp#579] opened 2021-03-09 18:20 UTC
**Describe the Bug**
After installing the App have the Browser features but you are in the app without BBD

**To Reproduce**
Install BBD close discord, open discord than you don't have BBD, close discord and open it again and you have the website version in your app.

**Expected Behavior**
BBD is successfully installed but no .-.

**Screenshots**
N/A

**Discord Version**
 Canary

**Additional Context**
N/A

**Comment by skullmaster2017** [comment] 2021-03-09 20:29
i have same problem

**Comment by rauenzi** [comment] 2021-03-09 20:58
This is a duplicate of #548

**Closed** 2021-03-09 20:58 UTC
Labels: bug
