### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by CrazyWillBear** [rauenzi/BetterDiscordApp#823] opened 2021-06-04 03:56 UTC
**Describe the Bug**
I updated to the latest version if DiscordCanary and as of the latest update (0.0.124), it won't start due to a JavaScript error:

**To Reproduce**
Update to version 0.0.124 and start DiscordCanary with BetterDiscord installed

**Expected Behavior**
It should have started properly

**Screenshots**
![screenshot of betterdiscord error](https://user-images.githubusercontent.com/16143570/120743611-2f309a00-c4ae-11eb-9422-cce771455149.png)

**Discord Version**
Canary

**Additional Context**
I am on Arch Linux, although this should have no affect.

**Comment by QbDesu** [comment] 2021-06-04 05:14
duplicate of #821

**Closed** 2021-06-04 06:34 UTC
Labels: bug
