### ISSUE TITLE
[Bug] Stable not working with Better Discord

### ISSUE THREAD

**Issue by mighelce** [rauenzi/BetterDiscordApp#589] opened 2021-03-17 23:37 UTC
**Describe the Bug**
So, today my discord updated and it's happening what people experienced in Canary, like, discord turning into the web app and the bar to close and minimize it's not showing up. It's the same thing but on the Stable version.

**To Reproduce**
I had my discord like this, then i unninstalled and installed again, right when i installed everything was fine and i installed bandagebd again, then the discord asks me to update, whenever i update it bugs everything since has BD in it. The bar does not show and all that stuff. And if i unninstall discord again everything comes back. I'm mutted all the time also. It's the same thing that in #548 but in stable version

**Screenshots**

**Discord Version**

**Comment by Tropix126** [comment] 2021-03-17 23:41
Duplicate of #585 #587 #548 #579 #577 #565 #563 #561 #551.

**Comment by mighelce** [comment] 2021-03-17 23:48
> Duplicate of #585 #587 #548 #579 #577 #565 #563 #561 #551.
Actually it's not the quite same thing. It's happening to me on stable version.

**Comment by Tropix126** [comment] 2021-03-17 23:53
Ah, there have been reports of discord pushing the new elecron version to users in an early rollout. Might want to have a look at this for the time being.
![image](https://user-images.githubusercontent.com/42101043/111553304-15ef3b80-8752-11eb-8138-4fcdc83a543c.png)
(patch link) https://cdn.discordapp.com/attachments/410788958277074944/821690118468272168/patch.zip

**Comment by mighelce** [comment] 2021-03-18 00:45
It worked thanks! But i would like to know whats the elecron version

**Comment by karma12gaming** [comment] 2021-03-21 22:30
> 
> 
> Ah, there have been reports of discord pushing the new elecron version to users in an early rollout. Might want to have a look at this for the time being.
> ![image](https://user-images.githubusercontent.com/42101043/111553304-15ef3b80-8752-11eb-8138-4fcdc83a543c.png)
> (patch link) https://cdn.discordapp.com/attachments/410788958277074944/821690118468272168/patch.zip

Thank you this worked for me as well.

**Comment by CheckisCheck** [comment] 2021-03-24 00:31
> Ah, there have been reports of discord pushing the new elecron version to users in an early rollout. Might want to have a look at this for the time being.
> ![image](https://user-images.githubusercontent.com/42101043/111553304-15ef3b80-8752-11eb-8138-4fcdc83a543c.png)
> (patch link) https://cdn.discordapp.com/attachments/410788958277074944/821690118468272168/patch.zip

This doesn't work for me

**Comment by rauenzi** [comment] 2021-03-31 21:15
Try to install BetterDiscord using this new beta installer: https://github.com/BetterDiscord/Installer

**Closed** 2021-04-02 17:09 UTC
Labels: bug
